apiVersion: v1
kind: Service
metadata:
  name: service-faces-postgres
  namespace: gallery
spec:
  selector:
    app: service-faces-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
