version: '3'
services:
  service-categories:
    image: "docker.redby.fr/gallery/service-categories:latest"
    volumes:
      - /gallery:/gallery
    ports:
      - "8083:8083"
  service-albums:
    image: "docker.redby.fr/gallery/service-albums:latest"
    volumes:
      - /gallery:/gallery
    ports:
      - "8084:8084"
  service-pictures:
    image: "docker.redby.fr/gallery/service-pictures:latest"
    volumes:
      - /gallery:/gallery
    ports:
      - "8085:8085"
    deploy:
      replicas: 5
  service-statistics:
    image: "docker.redby.fr/gallery/service-statistics:latest"
    volumes:
      - /gallery:/gallery
    ports:
      - "8086:8086"
  web-ui:
    image: "docker.redby.fr/gallery/web-ui:latest"
    ports:
      - "4200:4200"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  redis:
    image: redis
    restart: always
  service-scheduler:
    image: "docker.redby.fr/gallery/service-scheduler:latest"
    ports:
      - "8080:8080"