version: '3'
services:
  service-categories:
    image: "docker.redby.fr/gallery/service-categories:latest"
    volumes:
      - ${GALLERY_PATH}:/gallery
    ports:
      - "8083"
  service-albums:
    image: "docker.redby.fr/gallery/service-albums:latest"
    volumes:
      - ${GALLERY_PATH}:/gallery
    ports:
      - "8084"
  service-pictures:
    image: "docker.redby.fr/gallery/service-pictures:latest"
    volumes:
      - ${GALLERY_PATH}:/gallery
    ports:
      - "8085"
    deploy:
      replicas: 2
  service-statistics:
    image: "docker.redby.fr/gallery/service-statistics:latest"
    volumes:
      - ${GALLERY_PATH}:/gallery
    ports:
      - "8086"
  #web-ui:
  #  image: "docker.redby.fr/gallery/web-ui:latest"
  ionic-app:
    image: "docker.redby.fr/gallery/ionic-app:latest"
    ports:
      - "80"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017"
  redis:
    image: redis
  service-scheduler:
    image: "docker.redby.fr/gallery/service-scheduler:latest"
    ports:
      - "8080"
  reverse-proxy:
    image: "docker.redby.fr/gallery/reverse-proxy:latest"
    #  dockerfile: Dockerfile
    ports:
      - "${GALLERY_PORT}:80"
