name: First Issue Message

on:
  issues:
    types: [opened]

jobs:
  first_issue_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-docker-action@main
        with:
          who-to-greet: Stranger

  first-interaction:
    runs-on: ubuntu-latest
    steps:
      - name: first-interaction
        id: first-interaction
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            # Message with markdown.
            This is the message that will be displayed on users' first issue.
          pr-message: |
            Message that will be displayed on users' first pr.
            Look, a `code block` for markdown.
