# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven 2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build parent
      run: mvn clean install

    - name: Build categories
      working-directory: service-categories
      run: mvn clean install

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-markdown
        path: "**/*.jar"
      
  archive:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.example_step.outputs.result }}
      output2: ${{ steps.sets-a-secret.outputs.secret-number }}

    steps:
      # ENV Vars
      - name: Set the value in env vars
        run: echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value from env vars
        run: printf '%s\n' "$action_state" # This will output 'yellow'
      # Grouping messages
      - name: Grouping messages
        run: |
          echo "::group::This is a grouped message"
          echo "This is the content of the group"
          echo "And a new line"
          echo "And another line"
          echo "::endgroup::"
      # Output
      - name: Set output
        id: example_step
        run: echo "result=output_value" >> $GITHUB_OUTPUT
      - name: Use output
        run: echo "The output was ${{ steps.example_step.outputs.result }}"
      # Toolkit functions
      - name: Create messages
        run: | 
          echo "::debug::This is a debug Message"
          echo "::notice::This is a notice Message"
          echo "::warning::This is a warning Message"
          echo "::error::This is an error Message"
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
          the_secret=$((RANDOM))
          echo "::add-mask::$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      - name: Print the secret output (protected by a mask)
        run:  echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use the outputs from job1
        run: | 
          echo "The output1 from job1 was ${{ needs.job1.outputs.output1 }}"
          echo "The secret value is ${{ secrets.DB_PASSWORD }}"
      - name: Generate random number
        id: gen1
        uses: yakubique/random-number@v1.1
        with:
          min: 1
          max: 100
      - name: Show the number from the previous step
        run: | 
          echo "The output from gen1 was ... ${{ steps.gen1.outputs.result }}"
