spring.application.name=thumbnails
server.port=8080
spring.jmx.enabled=false
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Albums service URL
albums.service.url=${ALBUMS_SERVICE_URL:http://service-albums:8000}

# Redis Configuration
spring.data.redis.host=${CACHE_HOST:service-cache}
spring.data.redis.port=${CACHE_PORT:6379}
spring.data.redis.timeout=2000ms

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=86400000
spring.cache.redis.key-prefix=thumb:
spring.cache.redis.use-key-prefix=true
