spring.application.name=thumbnails
server.port=8080
spring.jmx.enabled=false
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Albums service URL
albums.service.url=${ALBUMS_SERVICE_URL:http://service-albums:8000}
